trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
    - name: downloadRir
      value: $(Agent.TempDirectory)
    - name: workingDir
      value: $(Build.SourcesDirectory)

steps:

- task: DownloadSecureFile@1
  name: env_test
  displayName: 'Download env_test file'
  inputs:
      secureFile: 'env_test'

- task: CopyFiles@2
  inputs:
      SourceFolder: '$(downloadRir)'
      Contents: 'env_test'
      TargetFolder: '$(workingDir)'
  displayName: 'copy env_test file to Build Directory'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(b2605b44-43b2-45d1-8001-4808eb591e25)'
    KeyVaultName: 'ctcnonprodcds1306cc-kv'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  inputs:
    script: |
        pwd
        ls -ltra
        echo $(Password) > secret.txt
        sed '/^REACT_APP_ADMIN_PIN /s/=.*$/= $(adminpin)/' env_test

- task: CopyFiles@2
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'