# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
variables:
- name: workingDir
  value: $(Build.SourcesDirectory)
- name: downloadRir
  value: $(Agent.TempDirectory)
- name: buildDigitalChit
  value: $(workingDir)/packages/digital-chit/

steps:
- task: DownloadSecureFile@1
  name: env
  displayName: 'Download env file'
  inputs:
    secureFile: 'env'
  
- script: |
    echo "print file details"
    cd $(downloadRir)
    ls -la
    mkdir -p $(buildDigitalChit)
    echo "end of output"

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(downloadRir)'
    Contents: '**'
    TargetFolder: '$(buildDigitalChit)/.env'

- script: |
    echo "print file details"
    cd $(buildDigitalChit)
    ls -la
    echo "end of output"